Drop cache_mgr URI support, add squid-internal-mgr support
boynux/squid-exporter pull request #102
Opened 2024-09-17 16:52 UTC by dswarbrick

Drop obsolete `cache_mgr://` URI support, which will be removed in Squid 7. Implement support for `squid-internal-mgr` endpoint support via HTTP(S).

Fixes: #100
Obsoletes: #99

2025-05-04 07:11 UTC, boynux commented
Thanks  for this change. 

There is a merge conflict, also I left a comment about compatibility which I appreciate it if you take a look. 
btw, Do you mind adding a line to the README to introduce this new change as well?

2025-05-04 07:12 UTC, boynux requested changes

2025-05-04 07:12 UTC, boynux commented on collector/client.go
> +func NewCacheObjectClient(hostname string, port int, username, password string, headers []string) *CacheObjectClient {
Is there any reason switching from the request object to multiple arguments? 

For the context: I did this change a while ago to avoid changing the function signature when introducing new arguments (or removing one).

2025-05-04 07:12 UTC, boynux commented on collector/client.go
> +		fmt.Sprintf("http://%s:%d/squid-internal-mgr/", hostname, port),
is this backward compatible with older versions of squid?

2025-05-05 15:28 UTC, dswarbrick commented on collector/client.go
> +func NewCacheObjectClient(hostname string, port int, username, password string, headers []string) *CacheObjectClient {
Due to the age of this PR, I may have forgotten the exact reasons, but explicitly listing the params in the function signature makes the code easier to read and is more in line with traditional Go programming style. I think it's unlikely that this function signature will change often (if ever), since the current set of params pretty much covers all requirements. Also, despite `NewCacheObjectClient` being a publicly exported function, are there actually any downstream projects using this code as a library? AFAICT, it is only an exported function since it invoked by the `main` package of this exporter.

2025-05-06 05:25 UTC, boynux commented on collector/client.go
> +func NewCacheObjectClient(hostname string, port int, username, password string, headers []string) *CacheObjectClient {
I'm not aware if anyone uses this method in other projects, but I think I changed this function in the past a few times, so it's not very unlikely that it's going to change. Almost any new configuration may introduce a new parameter. I'll be happy to keep it this way, but I think we should changing it back if we ever need to change this signature again.

2025-05-06 05:26 UTC, boynux commented on collector/client.go
> +		fmt.Sprintf("http://%s:%d/squid-internal-mgr/", hostname, port),
Thank you for confirming, 2011 sounds old enough to risk the backward compatibility issues. I'm wondering why didn't I use this in the first place :)

2025-05-06 05:30 UTC, merged

2025-05-06 08:33 UTC, dswarbrick commented
@boynux It appears that you overlooked the **draft** status of this PR and merged it anyway. I actually still had a few refinements to make (including the function signature), and I had not yet updated the README as you requested.

It's not a big deal, but I'll need to submit a follow-up PR with the remaining changes that I intended.